### PR TITLE
reflection: spoken words sync by accounting for each word as 250ms

### PR DESCRIPTION
**Pull request by dantaeyoung**

### CODE REVIEW

**Comment by lmccart** [comment]
@dantaeyoung This should timed not by word, but by phrase. The current audio file assumes a new phrase starts every 5s, and then the entire duration of the audio file is 180s. So if there are 20 phrases, that's 20*5s meditation + 80s memories. Hope that's more clear.

**Comment by dantaeyoung** [comment]
@lmccart Ah I see, you're right / that makes sense! 

But one question: I listened to the `peaceful-carefreeF.wav` file and timed the phrases, which do play every 5 seconds. But at 00:35, the "See the remnants of old perspectives" phrase is longer than 5 seconds, which means that the next phrase "What place comes to mind when you feel carefree?" plays at 0:43 immediately afterwards, creating an inaccurate offset. 

00:05 Where in your body do you feel carefree?
00:10 Focus on that area.
00:15 Move your attention into it.
00:20 What color do you see?
00:25 What texture do you feel?
00:30 Can you trace the outline of it?
00:35 See the remnants of old perspectives that held you captive in this area. You move freely through them now. They get more and more frail the more you move.  
(offset created here; messages are no longer at 00:X5 or 00:X0 )
00:43 What place comes to mind when you feel carefree?
00:48 Imagine being in that place.

How do you want to handle this? We could assume that the [BODY AREA] section is always 10 seconds long? Or something else?

**Comment by lmccart** [comment]
@dantaeyoung ahh good catch! I am going to go through all of the text and break up longer sentences into shorter phrases so we don't have this problem. I might also extend the phrase interval a bit to give more padding. so if we can pull out the interval timing and the total duration timing as easily accessible variables, that would be great.

**Comment by lmccart** [comment]
@dantaeyoung Sorry, I wrote that too fast. I like your idea better, I think it's simpler. Can we also make the [PERSON] instruction 10s? Then I'll review the text to make sure none are more than 10s total.

**Comment by dantaeyoung** [comment]
Sounds good! Just updated this pull request with commit 090d23f~

**Comment by lmccart** [comment]
beautiful, love the commenting, thanks @dantaeyoung!

**Comment by dantaeyoung** [comment]
Thanks @lmccart ! It was fun

**Pull request merged**
